default: &default
  adapter: postgresql
  host: localhost
  username: dlee
  password:
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: search_api_dev

test:
  <<: *default
  database: search_api_test
